### PR TITLE
DecentHolograms support

### PR DESCRIPTION
**Pull request by toonystank**
- Moved hologram creation to different classes, 
- Added config boolean options `hooks.HolographicDisplays.enable` and `hooks.DecentHolograms.enable` 
- Improved HologramSupport class
- DecentHolograms support

**I tested and it's working**

### CODE REVIEW

**Review by Archy-X — CHANGES_REQUESTED** [review]
Minor formatting and config changes

**Comment by toonystank** [comment]
Fixed all requested changes. Added config option `hooks.HolographicDisplays.enable` and `hooks.DecentHolograms.enable`

**Comment by Archy-X** [comment]
I know this is really delayed but after merging master in I'm getting a startup error:
```java.lang.NoSuchMethodError: 'void com.archyx.aureliumskills.bstats.bukkit.Metrics.<init>(org.bukkit.plugin.java.JavaPlugin, int)'```

Do you know what you changed might cause this? There weren't any merge conflicts but it could also be something with the merge.

**Comment by toonystank** [comment]
Issue fixed by updating bstats to latest version. and I updated worldguard to latest because it was showing few vulnerabilities

**Comment by Archy-X** [comment]
Can you downgrade WorldGuard back to the previous version since I believe it doesn't work on Java 8. Plus the dependency is provided by the server so there shouldn't be vulnerabilities as the server has the new version.

**Comment by toonystank** [comment]
Yes I did downgrade

**Review by Archy-X — APPROVED** [review]
Looks good now
